### ISSUE TITLE
Error when vim start

### ISSUE THREAD

**Issue by tracyone** [tek/vim-ycm-vim#2]
```
error detected while processing /Users/tracyone/.vim/bundle/vim-ycm-vim/after/plugin/ycm_vim.vim:
line    7:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
NameError: name 'vim' is not defined
```

mac osx eicapitan 10.11.4

vim 7.4 with 1-1655

I use vim-plug to install vim-ycm-vim and vimomni.vim

```vim
Plug 'tek/vim-ycm-vim'
Plug 'c9s/vimomni.vim'
```

I am not familiar with python,but after add `import vim` solve this problem

```python
import sys
import vim
sys.path.append(vim.eval('module_dir'))
```

but after start vim another error show up:

```
Error detected while processing function ycm#vim#register:                      
line    4:                                                                      
Traceback (most recent call last):                                              
Error detected while processing function ycm#vim#register:                      
line    4:                                                                      
  File "<string>", line 1, in <module>                                          
Error detected while processing function ycm#vim#register:                      
line    4:                                                                      
  File "/Users/tracyone/.vim/bundle/vim-ycm-vim/python/ycm_vim.py", line 5, in <
module>                                                                         
Error detected while processing function ycm#vim#register:                      
line    4:                                                                      
    from ycm.completers.threaded_completer import ThreadedCompleter             
Error detected while processing function ycm#vim#register:                      
line    4:                                                                      
ImportError: No module named completers.threaded_completer 

```

**Comment by tek** [comment]
this plugin is horribly outdated, the YCM api is probably completely incompatible now, I guess I should delete the repository. sorry, but I haven't used YCM in ages.
